### PR TITLE
MacOS Homebrew installation and update instructions

### PR DESCRIPTION
**Pull request by BigOokie**
Fixes #
NA
Changes:
- Added instructions for installing and updating CX using Homebrew on MacOS

Does this change need to mentioned in CHANGELOG.md?
Not really

### CODE REVIEW

**Comment by BigOokie** [comment]
@amherag could you take a look at this PR - adds instructions for installing CX on MacOS using Homebrew. Makes it very straightforward and simple for MacOS users

**Comment by amherag** [comment]
It looks good but I have no idea why it's throwing an error (Travis).

**Comment by gz-c** [comment]
The build failed on the OS X machine,
https://travis-ci.com/skycoin/cx/jobs/169348255

The error is during dependency installation through homebrew. It seems that the homebrew install is broken (this is unrelated to the PR). It may be a transient issue or the .travis.yml file is not configured correctly

**Comment by BigOokie** [comment]
Just looked over the Travis log. Interestingly I had exactly the same Homebrew error on my local machine today while trying to install ngrok (totally unrelated).

Wonder if Homebrew itself is broken?

**Comment by amherag** [comment]
I have been doing some research and some people report that they needed to upgrade their Ruby installation. Others reported needing to reset the homebrew repo. Is Travis running on a `ssh`-able machine or does everything need to be handled through the travis configuration file in this repo?

**Pull request merged**
