### PR TITLE
Fixes #97 #130 Add MacOS to build matrix and Run cx tests

### LINKED ISSUE #97: Continuous integration in Travis for MacOS and build matrix
Extend the work started in #12 to create a build matrix incorporating macos builds.

### PR DESCRIPTION
**Pull request by stdevYuniers**
Fixes: #97 #130 

Changes:
- Add `osx` to Travis matrix build
- Change way to install dependencies
- Mod appveyor file to improve doc

Does this change need to mentioned in CHANGELOG.md?

No

### CODE REVIEW

**Comment by olemis** [comment]
@amherag it seems `snyk` tests are failing

**Comment by amherag** [comment]
> 
> 
> @amherag it seems `snyk` tests are failing

`snyx` tests? by the way, now I remember that @asahi3g added tests for issues that have not been solved yet (I'll move the the tests known to be buggy to somewhere else). Another thing, what does Travis/Appveyor expect to consider a test as a failed test or a successful test? An error code?

Currently, CX runs the tests and it will inform in the terminal which tests passed and which didn't. I don't know if this will always be considered as a successful run of tests.

**Comment by olemis** [comment]
screen shot 2018-12-09 at 12 41 21 am
@amherag snyk tests failing

**Comment by olemis** [comment]
Depends on process exit code . Success = 0 . Failure = anything else

**Comment by olemis** [comment]
> I'll move the the tests known to be buggy to somewhere else

What I recommend is either 

- to move failing tests to a separate feature branch in which it is meant to be solved .
- create a single issue to fix'em all and a new feature branch accordingly

Thing is that if the test suite is not completely green that will block merging .

**Comment by amherag** [comment]
About `snyk`, I don't know why. We don't even have a `cxweb` directory anymore. We used to have cx.skycoin.net's code in this repository.

**Comment by amherag** [comment]
> 
> 
> > I'll move the the tests known to be buggy to somewhere else
> 
> What I recommend is either
> 
>     * to move failing tests to a separate feature branch in which it is meant to be solved .
> 
>     * create a single issue to fix'em all and a new feature branch accordingly
> 
> 
> Thing is that if the test suite is not completely green that will block merging .

I'll follow your recommendation.

**Comment by olemis** [comment]
> About snyk [...] We don't even have a cxweb directory anymore.

Pls disable `snyk` bot then (I can't ... @gz-c can you?) . The error is triggered (maybe) because there's nothing to check.

**Comment by olemis** [comment]
@amherag any ideas why [these errors](https://travis-ci.com/skycoin/cx/jobs/163859099#L1627-L1651) happening ? Do you vendor go packages with [dep](https://github.com/golang/dep) ?

**Comment by asahi3g** [comment]
> > I'll move the the tests known to be buggy to somewhere else
> 
> What I recommend is either
> 
>     * to move failing tests to a separate feature branch in which it is meant to be solved .
> 
>     * create a single issue to fix'em all and a new feature branch accordingly
> 
> 
> Thing is that if the test suite is not completely green that will block merging .

We can add a ++noknownissues flag to remove known failing issues when tests are run by travis ?

> Depends on process exit code . Success = 0 . Failure = anything else

I'll update de exit code of tests/main.cx accordingly

**Comment by olemis** [comment]
@asahi3g 👍 ... though I'd rather choose a way to include / exclude filters like ++includetests stable ... e.g. see https://github.com/skycoin/skycoin/issues/1897

**Comment by olemis** [comment]
@asahi3g If include / exclude filters are the way to go, that feature deserves a separate issue on its own

**Comment by gz-c** [comment]
where is the cxweb code?

**Comment by gz-c** [comment]
snyk disabled for cx

**Comment by olemis** [comment]
@amherag was this merged already ? Tha [last Travis build](https://github.com/skycoin/cx/runs/39261921) I can see in the feed looked like failing . Is this issue solved by now ?

**Pull request merged**
