### PR TITLE
[cxgo] fixes #141 fixes #75 - Changes in lexer and parser related to signed literals

### LINKED ISSUE #75: can't prefix a (f32) variable with minus to flip it's signedness
it gives no error, but doesn't work.

however, you CAN prefix a literal (f32 number) this way, and that DOES work.

### LINKED ISSUE #141: Parser gets confused with `2 -2`
For example:

```
package main

func main () {
	var foo i32
	foo = 5 -3

	i32.print(foo)
}
```

throws `examples/testing.cx:5: syntax error: unexpected INT_LITERAL`

Most likely the parser is interpreting `5 -3` as two consecutive `INT_LITERAL`s: `5` and `-3` without any operator in-between.

### PR DESCRIPTION
**Pull request by olemis**
Fixes #141 fixes #75 

Changes:
- Integer literals are always positive
- Negative literals parsed and evaluated as unary `SUBOP` + literal
- New non-terminal `int_value` for non-expression statements that rely on (signed) integer constants
- `make update-golden-files` will not fail if lexer fails for individual files  (in order to generate them all at once)
- Add `OP_*_NEG` op codes for unary arithmetic negation
- `op*Sub` and `op_sub` implement `OP_*_SUB` and `OP_*_NEG`
- `IsUndOp(OP_UND_NEG) = true`
- `CheckArithmeticOp(OP_I32_NEG) = true`
- Updated lexer golden files

Does this change need to mentioned in CHANGELOG.md?
yes

### CODE REVIEW

**Comment by olemis** [comment]
@amherag still WiP

**Comment by ingwal** [comment]
I think the changes in this PR are good, and I'm very much in favour of merging them.  That said...
1. I don't think that we should combine whitespace changes with function changes in this way.  Especially the real changes in op_und.go are almost impossible to see.
2. I don't think we should combine style changes like the import lines with functional changes in this way.
Can we please separate these types of changes in the future to make it easier to review?

**Comment by olemis** [comment]
@ingwal your arguments look like reasonable  at first glance , but beware of the fact that

- **All** Skycoin projects have to meet some coding style standards and current CX code base does not
- #201 is aimed at fixing those, and has to be merged prior to all other open PR's
  * we working on that right now , the delay is due to the so many violations found
- developers (like everybody in our team, so I recommend you to do so) should have their IDE's setup configured for enforcing the standards
- ... and once the former configuration is done it will be impossible (like it is for me now) to push code that does not meet them

Summarizing , changes are in line with Skycoin standards, they are the correct

**Comment by olemis** [comment]
The right thing to do is to wait for merging the PR fixing #201 . Once these changes will be in `develop` only meaningful differences will be reported in this PR .

**Pull request merged**
